### PR TITLE
updated color for gender #148

### PR DESCRIPTION
**Pull request by bikramkawan**
@mijar @katush  changed color in gender

### CODE REVIEW

**Comment by katush** [comment]
Much better! Though I would choose more "gender associated color". Or is that avoided on purpouse?
e.g: https://s-media-cache-ak0.pinimg.com/originals/d4/8d/c0/d48dc042b55c22ec5e4025cbe2900155.jpg

**Comment by bikramkawan** [comment]
It was not avoided. It was taken from the colorbrewer. Could you write down the actual color name as in your  picture

**Comment by katush** [comment]
Group #ffe1a3,  Male #1d9ee8 Female#d97979, Should be also colorblidsafe.

**Comment by bikramkawan** [comment]
image

**Pull request merged**
