### PR TITLE
Sort testing on  Numerical,Categorical,String by Asc and Desc #3

### PR DESCRIPTION
**Pull request by bikramkawan**
TO DO : The sort is not applied on matrix.

### CODE REVIEW

**Comment by mstreit** [comment]
@bikramkawan, please create a new issue for sub-features that are not addressed yet.

**Comment by bikramkawan** [comment]
@mijar @katush Please test on your side.

**Comment by mstreit** [comment]
@bikramkawan, I suggest to remove the sorting icons from the matrix block's toolbar.

**Comment by bikramkawan** [comment]
ok

**Pull request closed without merging**
