### PR TITLE
Column relayout

### PR DESCRIPTION
**Pull request by sgratzl**
don't forget to update your dependencies (phovea_core, phovea_vis)

### CODE REVIEW

**Comment by mstreit** [comment]
I wanted to test it but it does not work for me locally. after switching to this branch, this is what I did to update the dependencies:
1. ./forEach git pull
2. yo phovea:update
3. npm install
4. docker-compose build api
5. docker-compose up -d
6. npm run start:mothertable

build error:
```
ERROR in [default] /Users/marcstreit/phovea/mothertable/mothertable/src/SupportView.ts:6:8
Module '"/Users/marcstreit/phovea/mothertable/phovea_core/src/vector"' has no exported member 'ICategoricalVector'.
```

@sgratzl, what is the problem here?

**Comment by sgratzl** [comment]
your `phovea_core` is not in the develop branch as it should be

**Comment by mstreit** [comment]
Should all `phovea_*` repos be in the develop branch or just `phovea_core`?

**Comment by sgratzl** [comment]
https://github.com/Caleydo/mothertable/blob/master/package.json#L69

**Comment by mijar** [comment]
I am getting this: 
`Async functions are only available when targeting ECMAScript 2015 or higher.` on 
`npm run start:mothertable`
and cannot move forward, everything is up-to-date and goes through successfully

**Comment by mstreit** [comment]
@mijar, just set it up freshly with the single command `yo phovea:setup-workspace mothertable_product` and switch the branch of the mothertable repo within the workspace. Worked for me.

@sgratzl, I don't see an improvement of the height behaviour in this branch:
image

**Comment by mijar** [comment]
thanks @mstreit , works now...

I also see the same behavior of the columns, the one added as a first one also is not scaled

**Comment by mstreit** [comment]
@sgratzl, can you please explain what should be different now?

**Comment by mstreit** [comment]
This is how it looks on @sgratzl's local setup:
gif

So it seems that our state is not properly compiled after switching to the relayout branch.

**Comment by mstreit** [comment]
@mijar @katush, we are working on this. I will report here as soon as it is clear what is going on here.

**Comment by mstreit** [comment]
@mijar or @katush , sam's commit fixed the problem. just pull, test and merge it into the master.

**Comment by mijar** [comment]
works in my workspace too, like the commit message :-) Merging

**Pull request merged**
