### PR TITLE
Sorting button 69

### PR DESCRIPTION
**Pull request by mijar**
#69 addressed, ready for integration of sorting functionality that Bikram previously created...

@bikramkawan

### CODE REVIEW

**Comment by bikramkawan** [comment]
image
Is this icon only for ascending and descending? Will there be another icon to sort boxplot values?

**Comment by mijar** [comment]
How would you like it to look like and work? Ideas?

**Comment by mstreit** [comment]
There are two different features that are related to sorting: 
- change sorting direction (ascending and descending) - could be indicated via a tiny arrow pointing up or down. The columns that is sorted, will also be the top one in the sorting hierarchy (which will also change the order of filters in the filter view on the right)
- change sorting criterion (min, max, median, etc.) -> should only be added for aggregated columns (can be a separate issue)

**Comment by bikramkawan** [comment]
image
This should be changed into radio button selection.For now, I have just merged it.

**Pull request merged**
