### PR TITLE
Bugfix for duplicating vis when building state from URL hash

### PR DESCRIPTION
**Pull request by thinkh**
Please confirm if this fixes the problem -- at least in my tests it is working as expected.

taggle_reload-from-hash

**Explanation**
While waiting for some results from `await` the columns have been changed and thus used a wrong number of columns when splitting the multiforms. I tried to avoid using the class variable `this.filterHiearchy`. Instead I sliced a copy so that I can ensure the elements (https://github.com/Caleydo/mothertable/compare/thinkh/bugfix-loading-from-hash?expand=1#diff-5af33055eeb4b6024eada05612cd2bceR158) and passed these columns directly from function to function.

### CODE REVIEW

**Comment by mstreit** [comment]
No duplicates. But the scaling is messed up:

image

Why is that not happening in the screencast?

**Comment by thinkh** [comment]
@mstreit I don't know. Could you please give a URL or steps to reproduce your state?

**Comment by mstreit** [comment]
It happens for both URLs listed in #209

**Comment by thinkh** [comment]
Ok, I'll check those URLs

**Comment by mstreit** [comment]
It's not deterministic. Sometimes it works.

**Comment by mstreit** [comment]
This is a scaling and update issue, which is probably unrelated to the URL restoring.

**Comment by thinkh** [comment]
Yes, true. Anyway there is a bug that matrices do not appear and barplots have negative values.

**Comment by thinkh** [comment]
I will see why matrices are not restored correctly. The other errors are a different PR.

**Comment by bikramkawan** [comment]
Seems working for me . Thanks @thinkh 👍 
mar-16-2017 6-54-47 pm

**Pull request merged**
