### PR TITLE
quick fix  #119

### LINKED ISSUE #119: Data missing after filter applied on missing value
There is a bug in filter for missing value data.
Use case:
1.Add Origin
2.Add age (years)
Total entries => 12
3. Filter US
Total entries => 2 
4. Unfilter US
Total entries => 8 instead of 12.

### PR DESCRIPTION
**Pull request by bikramkawan**
@mijar @katush Please check on your side.

### CODE REVIEW

**Comment by katush** [comment]
Causes reordering of the data.
Use case:
1.Add Origin
2.Add age (years) :
image
3. Filter US
4. Unfilter US:
image

It seems it is sorted by ID treated as string.

**Comment by bikramkawan** [comment]
Did you apply any sorting?  The data is displayed correctly as in dataset. What did you expect ?

**Comment by mstreit** [comment]
yes, @katush is right. 10,11 should appear at the end of the list. it is because you sort IDs as strings (where 10 comes after 1 and before 2).

**Comment by mstreit** [comment]
in any case the ID should not appear within the age multiform visualization.

**Comment by mstreit** [comment]
if a vector is a number, also sort is by number. if a vector is a string, sort it by alphabet.
in the case of the age column, it should be sorted by the age obviously (and not the ID)

**Comment by bikramkawan** [comment]
image

So this is after sorting applied. Initially, there is no sorting applied, and I don't know how the data are treated for visualization on phovea vis if there is no particular sorting applied.

**Comment by katush** [comment]
I believe there should always be some initial sorting. If we claim that the order in filtering view reflects the sorting hierarchy, that should be true from the very beginning, shouldn't it?

**Comment by bikramkawan** [comment]
Yes this was the question I rise last time.  I will update once the sorting is done. The default sorting is ASC.

**Pull request merged**
