### PR TITLE
Feature #212

### PR DESCRIPTION
**Pull request by katush**
Magic box basic functionality #212

### CODE REVIEW

**Comment by thinkh** [comment]
I get the following browser error(s) when adding a categorical column that is shown as mosaic plot:

```
Uncaught (in promise) TypeError: Cannot read property 'attr' of undefined
    at Mosaic.webpackJsonp.255.Mosaic.drawLabels (http://localhost:8080/3.js:540:20)
    at Mosaic.webpackJsonp.255.Mosaic.transform (http://localhost:8080/3.js:534:14)
    at MultiForm.transform (http://localhost:8080/app.js:32048:37)
    at ZoomLogic.zoomSet (http://localhost:8080/app.js:38634:23)
    at ZoomLogic.zoomTo (http://localhost:8080/app.js:38647:21)
    at Event.onReady_1 (http://localhost:8080/app.js:24815:18)
    at SingleEventHandler.fire (http://localhost:8080/app.js:1002:22)
    at MultiForm.EventHandler.fireEvent (http://localhost:8080/app.js:1107:22)
    at http://localhost:8080/app.js:1100:19
    at Array.forEach (native)
```

taggle_labels-error

@katush Any ideas?

**Comment by thinkh** [comment]
Demonstration of the bug:

taggle_mosaic-error

**Comment by katush** [comment]
seems to be caused by my code for adding labels to mosaic plot, sorry, going to fix now

**Comment by thinkh** [comment]
@katush Did you fix that bug in the mosaic plot?

**Comment by thinkh** [comment]
@katush I fixed the exception with that commit https://github.com/phovea/phovea_vis/commit/e6b3468745596d0e16ec571953c4d56c56e5e70d. The problem was that `markReady()` was triggered before the labels are initialized. Now I initialize the labels first and then send the ready event (which at the end triggers the Mosaic.transform).

Now I still have the error that no labels are shown. The DOM elements exists, but the group has `display="none"`. I assume that one of the categories is too small to show the label and therefore all labels are hidden. The improvement would be that you check for each block/rect individually if the text can be shown. Could you please have a look again?

I will continue reviewing the PR.

**Comment by thinkh** [comment]
@katush How can I test your implementation? I added some columns and resized my browser window, but nothing happens.

taggle_magic-box

**Comment by thinkh** [comment]
Filtering out some elements worked. The visualization is changing depending on the number of elements. However, as described above it is not changing when resizing the window.

**Pull request merged**
