### PR TITLE
Several style fixes for the AggSwitcher column and the column header

### LINKED ISSUE #300: Aggregation switcher should consider height of meta-rows added on top of matrix
image

### PR DESCRIPTION
**Pull request by thinkh**
Fixes #300

grafik

### CODE REVIEW

**Comment by mijar** [comment]
The header is being moved down in the matrices now...
image

**Comment by thinkh** [comment]
@mijar I can confirm that. I see if I can fix it.

**Comment by mstreit** [comment]
we already have an issue for this:
https://github.com/Caleydo/mothertable/issues/310

**Comment by thinkh** [comment]
@mijar Fixed with the last commit to master.

**Pull request merged**
