### PR TITLE
Configure setup based on URL hash 

### PR DESCRIPTION
**Pull request by thinkh**
See #189

**Features**

* Store idtypes and selected filters
* Filter hierarchy is reflected in the hash (order of filters)
* Restore on reloading

**Limitations**

* The order of the columns in the main view is not stored
* Filters are not stored in the hash

[Example URL](http://localhost:8080/#idtype=artist&artist=origin%2Cgender%2Ccareer%20status%2Cartist)

taggle_url-hash

### CODE REVIEW

**Comment by thinkh** [comment]
Example URLs are collected in #209.

**Comment by mstreit** [comment]
Works in general. But I run into a duplication issue when testing it with this URL:
http://localhost:8080/#idtype=TCGA_SAMPLE&TCGA_SAMPLE=Methylation%2Cpatient.gender%2CmRNA%2Cpatient.daystolastfollowup

image

**Comment by thinkh** [comment]
@mstreit Please test again. In my setup it's fixed with the last commit.

**Comment by mstreit** [comment]
Works now as expected.

**Pull request merged**
