### PR TITLE
Update the category order in filter view by sorting criteria

### PR DESCRIPTION
**Pull request by bikramkawan**
@katush @mijar Please check on your side.

### CODE REVIEW

**Comment by mijar** [comment]
@bikramkawan add also a listener onto the sorting icon in the header of columns....right now it works only for the icons in Filter View

**Comment by bikramkawan** [comment]
@mijar @katush Ping

**Comment by katush** [comment]
@bikramkawan please look at the failed travis checks

**Comment by bikramkawan** [comment]
@katush fixed travis

**Pull request merged**
