### PR TITLE
Add value type icons

### PR DESCRIPTION
**Pull request by thinkh**
Added value type icons:

grafik

grafik

### CODE REVIEW

**Comment by mstreit** [comment]
Looks good. I am not sure if I like the icons so much ;)

**Comment by mstreit** [comment]
How about those:
- Categorical: http://fontawesome.io/icon/bars/
- Numerical: http://fontawesome.io/icon/list-ol/ (not sure about this one)
- Matrix: http://fontawesome.io/icon/th/

**Comment by thinkh** [comment]
For numerical I suggest this http://fontawesome.io/icon/signal/ rotated by
90 degrees.

I can change the items tomorrow.

**Comment by thinkh** [comment]
See #294

**Pull request merged**
