### PR TITLE
preview of data lost #94

### PR DESCRIPTION
**Pull request by bikramkawan**
@mijar @katush Please check on your side.

### CODE REVIEW

**Comment by mijar** [comment]
remove the divs if there are no columns in table view, check the width of the element after adding first column (it is slighty smaller)

**Comment by bikramkawan** [comment]
I have update please check once now. @mijar @katush

**Comment by mijar** [comment]
it's not working now...I added a few columns from the artists ID type, filtered something, added it again and it is not showing the whole dataset..

**Comment by bikramkawan** [comment]
After you filtered and added why would it show the whole dataset? It Will it only show the portion of current data available, is not it?
feb-16-2017 1-27-46 pm

**Comment by mijar** [comment]
solved, it was related to a different issue but combining codes with master helped - the fix was already there.

**Pull request merged**
