### PR TITLE
Feature filter dialog

### PR DESCRIPTION
**Pull request by bikramkawan**
@katush @mijar 
Please have a look and test in your machine and let me know if there are some bugs.

### CODE REVIEW

**Comment by mijar** [comment]
When you add an attribute twice, it appears only once in the fiter view, which is correct - the problem is when you want to delete one instance of this attribute in table view and keep the other - the corresponding block in the filter view disappears
1attrtwice

**Comment by mstreit** [comment]
Let's file an issue for this problem and merge this branch anyway.

**Comment by mijar** [comment]
I have created it couple seconds ago and will add issues for other things I have come over.
It is not critical, so I will surely merge it soon

**Comment by bikramkawan** [comment]
For the issue regarding the filter dialog remove.
See here:
https://github.com/Caleydo/mothertable/pull/48

**Pull request merged**
